---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-sensu-go-cli
      sensu_cli_assets:
        - name: sensu/sensu-slack-handler:1.0.3
          rename: sensu-slack-handler
        - name: sensu-plugins/sensu-plugins-cpu-checks
